(function(){
  "use strict";
  const pages={
    "index.html":{key:"dashboard",title:"Рабочий стол",eyebrow:"Операционная зона · сегодня, 28 июня",subtitle:"Доброе утро, Анна. Система работает стабильно, 3 заявки требуют внимания."},
    "queue.html":{key:"queue",title:"Очередь записей",eyebrow:"Распределение нагрузки",subtitle:"Три независимых потока: каждый монитор продолжает работу отдельно."},
    "customers.html":{key:"customers",title:"Клиенты",eyebrow:"Клиентский контур",subtitle:"История обращений и текущий контекст без переходов между системами."},
    "monitoring.html":{key:"monitoring",title:"Мониторинг",eyebrow:"Наблюдаемость",subtitle:"Ключевые сервисы и каналы в одном потоке. Красное — действие, жёлтое — наблюдение."},
    "notifications.html":{key:"notifications",title:"Уведомления",eyebrow:"Центр внимания",subtitle:"Сигналы, которые помогают не держать всё в голове."},
    "events.html":{key:"events",title:"Журнал событий",eyebrow:"Наблюдаемость · аудит",subtitle:"Единая хронология действий операторов, клиентов и системных процессов."},
    "system.html":{key:"system",title:"Статус системы",eyebrow:"Контроль инфраструктуры",subtitle:"Состояние сервисов, фоновых задач и последнего резервного копирования."},
    "settings.html":{key:"settings",title:"Настройки",eyebrow:"Рабочее пространство",subtitle:"Локальные параметры операционного центра сохраняются на этом устройстве."},
    "reports.html":{key:"reports",title:"Отчёты",eyebrow:"Данные для решений",subtitle:"Операционная картина без ручной сборки таблиц: нагрузка, скорость и результат."},
    "shifts.html":{key:"shifts",title:"Смены",eyebrow:"Команда на линии",subtitle:"Кто сейчас отвечает за поток, когда передавать заявки и где оставить контекст."},
    "quality.html":{key:"quality",title:"Контроль качества",eyebrow:"Стандарт обслуживания",subtitle:"Выборочная проверка завершённых записей и обратная связь операторам."},
    "integrations.html":{key:"integrations",title:"Интеграции",eyebrow:"Внешние контуры",subtitle:"Сервисы, на которые опирается операционная команда. Статус виден до того, как он станет проблемой."}
  };
  const nav=[["Операционная зона",[["Рабочий стол","index.html","dashboard","home"],["Клиенты","customers.html","customers","users"],["Очередь записей","queue.html","queue","clock"],["Мониторинг","monitoring.html","monitoring","monitor"],["Уведомления","notifications.html","notifications","bell","2"],["Журнал событий","events.html","events","file"]]],["Контроль",[["Статус системы","system.html","system","pulse"],["Отчёты","reports.html","reports","chart"],["Смены","shifts.html","shifts","calendar"],["Контроль качества","quality.html","quality","shield"],["Интеграции","integrations.html","integrations","network"],["Настройки","settings.html","settings","settings"]]]];
  const queueRows=[
    ["ТО","Ткаченко Ольга Игоревна","Италия","Высокий","Оплата","6 мин","Подтвердить оплату","8 мин назад","amber"],
    ["ИП","Иванов Пётр Сергеевич","Испания","Высокий","Мониторинг","—","Проверка через 4 мин","2 мин назад","teal"],
    ["СА","Смирнова Анна Викторовна","Франция","Высокий","САРТЧА","—","Открыть САРТЧА","5 мин назад","amber"],
    ["В","Волкова Мария","Турция","Средний","Ожидание","14 мин","Назначить оператора","16 мин назад","blue"],
    ["КН","Ким Николай Андреевич","ОАЭ","Низкий","Новая","—","Начать обработку","21 мин назад","teal"],
    ["ПЕ","Петрова Елена","Греция","Средний","Документы","9 мин","Проверить документы","25 мин назад","blue"]
  ];
  const customers=[
    ["ТО","Ткаченко Ольга Игоревна","olga.t@inbox.ru","Италия","4","Сегодня, 11:42","В работе"],
    ["ИП","Иванов Пётр Сергеевич","p.ivanov@mail.ru","Испания","2","Сегодня, 11:37","Мониторинг"],
    ["СА","Смирнова Анна Викторовна","anna.smirnova@ya.ru","Франция","7","Сегодня, 11:21","В работе"],
    ["ВМ","Волкова Мария","m.volkova@mail.ru","Турция","1","Вчера, 18:05","Завершён"],
    ["КН","Ким Николай Андреевич","n.kim@inbox.ru","ОАЭ","3","Вчера, 16:48","Завершён"]
  ];
  const events=[
    ["11:57:24","Новая запись добавлена в очередь","Ткаченко Ольга Игоревна · Италия","Новая запись","teal"],
    ["11:54:08","Платёж подтверждён","Иванов Пётр Сергеевич · EUR 320","Платёж","amber"],
    ["11:49:32","Изменён приоритет заявки","САРТЧА · заявка #BK-2841","Изменение","blue"],
    ["11:46:10","Завершена проверка мониторинга","booking-gateway · 182 мс","Система","teal"],
    ["11:42:54","Оператор передал заявку","Михаил Орлов → Дарья Мельник","Смена","blue"],
    ["11:38:17","Документ загружен клиентом","Петрова Елена · паспорт","Документы","amber"],
    ["11:34:03","Создано уведомление","Высокое время ожидания · очередь #03","Алерт","red"]
  ];
  const notifications=[
    ["n1","Превышено время ожидания","Заявка Волковой Марии ожидает назначения оператора 14 минут.","2 мин назад",true,"red","Алерт"],
    ["n2","Смена заканчивается через 30 минут","Передайте заявки следующему оператору до 12:30.","18 мин назад",true,"amber","Смена"],
    ["n3","Синхронизация завершена","12 записей из внешних каналов добавлены в очередь.","42 мин назад",false,"teal","Система"],
    ["n4","Обновлена политика приоритета","Правило «сначала срочные» применяется к очереди по умолчанию.","Сегодня, 09:12",false,"blue","Система"]
  ];
  function icon(name){
    const p={home:"<path d='m3 10 9-7 9 7v10a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1z'/><path d='M9 21v-6h6v6'/>",users:"<path d='M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2'/><circle cx='9' cy='7' r='4'/><path d='M22 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75'/>",clock:"<circle cx='12' cy='12' r='9'/><path d='M12 7v5l3 2'/>",monitor:"<rect width='18' height='13' x='3' y='3' rx='2'/><path d='M8 21h8M12 16v5'/>",bell:"<path d='M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4'/>",file:"<path d='M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z'/><path d='M14 2v6h6M8 13h8M8 17h6'/>",pulse:"<path d='M3 12h4l2-7 4 14 2-7h6'/><path d='M3 5v14M21 5v14'/>",chart:"<path d='M4 19V5M4 19h16'/><path d='m7 15 3-4 3 2 4-6'/>",calendar:"<rect x='3' y='4' width='18' height='17' rx='2'/><path d='M16 2v4M8 2v4M3 10h18M8 14h.01M12 14h.01M16 14h.01M8 18h.01M12 18h.01'/>",shield:"<path d='M12 3 20 6v5c0 5-3.3 8.5-8 10-4.7-1.5-8-5-8-10V6z'/><path d='m8 12 2.5 2.5L16 9'/>",network:"<circle cx='12' cy='5' r='2'/><circle cx='5' cy='19' r='2'/><circle cx='19' cy='19' r='2'/><path d='M12 7v5M7 18l4-5M17 18l-4-5'/>",settings:"<path d='M12 15.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7z'/><path d='m19.4 15 .1.1a2 2 0 1 1-2.8 2.8l-.1-.1a2 2 0 0 0-3.4 1.4v.3a2 2 0 1 1-4 0v-.3a2 2 0 0 0-3.4-1.4l-.1.1a2 2 0 1 1-2.8-2.8l.1-.1A2 2 0 0 0 1.7 12 2 2 0 1 1 5 8.6a2 2 0 0 0 1.4-3.4V5a2 2 0 1 1 2.8-2.8l.1.1A2 2 0 0 0 12.7 1 2 2 0 1 1 16 4.4a2 2 0 0 0 3.4 1.4l.1-.1a2 2 0 1 1 2.8 2.8l-.1.1A2 2 0 0 0 23.3 12a2 2 0 1 1-3.4 3z'/>",menu:"<path d='M4 6h16M4 12h16M4 18h16'/>",refresh:"<path d='M20 11a8 8 0 1 0 2 5'/><path d='M20 4v7h-7'/>",check:"<path d='m5 12 4 4L19 6'/>",search:"<circle cx='11' cy='11' r='7'/><path d='m20 20-4-4'/>",filter:"<path d='M4 6h16M7 12h10M10 18h4'/>",plus:"<path d='M12 5v14M5 12h14'/>",more:"<circle cx='5' cy='12' r='1'/><circle cx='12' cy='12' r='1'/><circle cx='19' cy='12' r='1'/>",heart:"<path d='M20.8 8.6c0 5.4-8.8 10.4-8.8 10.4S3.2 14 3.2 8.6A4.6 4.6 0 0 1 12 6.2a4.6 4.6 0 0 1 8.8 2.4z'/>",life:"<circle cx='12' cy='12' r='9'/><path d='m12 8 1.5 3.5L17 13l-3.5 1.5L12 18l-1.5-3.5L7 13l3.5-1.5z'/>",spark:"<path d='m12 3 1.5 6.5L20 11l-6.5 1.5L12 19l-1.5-6.5L4 11l6.5-1.5z'/>",gauge:"<path d='M4 16a8 8 0 1 1 16 0'/><path d='m12 12 4-4M7 17h.01M12 18h.01M17 17h.01'/>"};
    return "<svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='1.8' stroke-linecap='round' stroke-linejoin='round'>"+(p[name]||p.more)+"</svg>";
  }
  function esc(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
  function button(label,cls="",ico=""){return `<button class="button ${cls}" data-action="toast" data-message="${esc(label)}">${ico?icon(ico):""}${label}</button>`}
  function link(label,href,cls="",ico=""){return `<a class="button ${cls}" href="${href}">${ico?icon(ico):""}${label}</a>`}
  function person(row,sub){return `<div class="person"><span class="person-avatar">${esc(row[0])}</span><div><div class="person-name">${esc(row[1])}</div>${sub?`<div class="subtext">${esc(sub)}</div>`:""}</div></div>`}
  function tag(text,tone=""){return `<span class="tag ${tone}">${text}</span>`}
  function metric(label,value,detail,tone=""){return `<div class="card metric ${tone}"><div class="metric-label">${label}</div><div class="metric-value">${value}</div><div class="metric-detail ${tone==="red"?"warn":"good"}">${detail}</div></div>`}
  function bars(values){return `<div class="trend">${values.map(v=>`<i class="bar" style="height:${v}%"></i>`).join("")}</div>`}
  function progress(value,cls=""){return `<div class="progress ${cls}"><i style="width:${value}"></i></div>`}
  function headerButton(page){
    if(page==="dashboard"||page==="queue"||page==="monitoring")return button("Обновить","","refresh");
    if(page==="customers")return button("Новый клиент","primary","plus");
    if(page==="notifications")return button("Отметить все прочитанными","","check");
    if(page==="events")return button("Экспорт журнала","","chart");
    if(page==="system")return button("Запустить проверку","","refresh");
    if(page==="settings")return button("Сохранить изменения");
    if(page==="reports")return button("Сформировать отчёт","primary","chart");
    if(page==="shifts")return button("Подготовить передачу","primary","calendar");
    if(page==="quality")return button("Новая проверка","primary","shield");
    return button("Проверить подключения","","refresh");
  }
  function shell(page,content){
    const p=pages[page], file=Object.keys(pages).find(k=>pages[k].key===page)||"index.html";
    const groups=nav.map(g=>`<div class="nav-group"><p class="nav-heading">${g[0]}</p>${g[1].map(n=>`<a class="nav-link ${n[2]===page?"active":""}" href="${n[1]}">${icon(n[3])}<span>${n[0]}</span>${n[4]?`<b class="nav-badge">${n[4]}</b>`:""}</a>`).join("")}</div>`).join("");
    return `<div class="app-shell"><aside class="sidebar" id="sidebar"><div class="brand"><div class="brand-mark">BO</div><div class="brand-name">Booking Ops</div></div>${groups}<div class="sidebar-foot"><div>Текущий доступ</div><span class="operator-pill">Оператор</span><div>Локальный демо-контур</div></div></aside><main class="main"><header class="topbar"><div style="display:flex;align-items:center;gap:11px"><button class="mobile-menu" data-action="menu" aria-label="Открыть меню">${icon("menu")}</button><div class="crumb">Операционный центр <span>/</span> <strong>${p.title}</strong></div></div><div class="top-actions"><div class="sync"><span class="sync-dot"></span> Синхронизировано <span id="sync-time">21:57</span></div><div class="notification-wrap"><button class="icon-button" data-action="bell" aria-label="Уведомления">${icon("bell")}<span class="count-dot">2</span></button><div class="notification-pop" id="notification-pop" hidden><p><strong>2 новых уведомления</strong><br>Превышено время ожидания и смена скоро заканчивается.</p><a class="button" style="width:100%" href="notifications.html">Открыть центр уведомлений</a></div></div><div class="avatar" title="Анна Кузнецова">АК</div></div></header><div class="page"><div class="page-heading"><div><p class="eyebrow">${p.eyebrow}</p><h1>${p.title}</h1><p class="subtitle">${p.subtitle}</p></div>${headerButton(page)}</div>${content}</div><div id="toast" class="toaster" hidden></div></main></div>`;
  }
  function dashboard(){
    return `<div class="dashboard-banner"><div><strong>Смена в активном режиме</strong><p>Вы на линии до 12:30 · 4 оператора онлайн · последняя передача 11:42</p></div>${link("Открыть смену","shifts.html","","calendar")}</div><section class="section metrics">${metric("Активные заявки","8","+2 за последний час","teal")}${metric("Высокий приоритет","3","требуют внимания первым","red")}${metric("Среднее ожидание","7,4 мин","на 1,2 мин меньше плана","blue")}${metric("Завершено сегодня","47","92% в пределах SLA","amber")}</section><section class="section split"><div class="card table-card"><div class="table-top"><div><h2>Очередь записей</h2><small>Следующие заявки для обработки</small></div>${tag("FIFO с приоритетом")}</div><div class="wide-list">${queueRows.slice(0,4).map((r,i)=>`<div class="queue-row"><span class="queue-num">${i+1}</span>${person(r,r[7])}<span class="priority-${r[3]==="Высокий"?"high":r[3]==="Средний"?"medium":"low"}">${r[3]}</span>${tag(r[4],r[8])}<a class="table-link" href="queue.html">Открыть</a></div>`).join("")}</div><div style="padding:14px 18px">${link("Открыть всю очередь","queue.html","","clock")}</div></div><div class="card card-pad"><div class="section-head"><div><h2>Активность</h2><small>Последние события</small></div><a class="table-link" href="events.html">Все</a></div><div class="activity-list">${events.slice(0,4).map(e=>`<div class="activity-item"><div class="activity-icon">${icon("pulse")}</div><div class="activity-copy"><strong>${e[1]}</strong><div class="subtext">${e[2]}</div><div class="activity-time">${e[0]}</div></div></div>`).join("")}</div></div></section><section class="section split"><div class="card card-pad"><div class="section-head"><div><h2>Пропускная способность</h2><small>Заявки за последние 8 часов</small></div><span class="kicker">47 всего</span></div>${bars([28,36,45,30,53,64,72,58,76,68,85,77,93,80,71,86])}<div class="stat-row"><span>Входящие</span><span>54</span></div>${progress("76%")}<div class="stat-row"><span>Завершённые</span><span>47</span></div>${progress("63%","amber")}</div><div class="card health-card"><div class="health-title"><div><h2>Здоровье системы</h2><div class="subtext">Обновлено минуту назад</div></div><span class="health-dot"></span></div><div class="check"><div><div class="check-name">Booking gateway</div><div class="check-meta">Средний ответ 182 мс</div></div><div class="check-status">${tag("Работает")}</div></div><div class="check"><div><div class="check-name">Платёжный шлюз</div><div class="check-meta">Средний ответ 241 мс</div></div><div class="check-status">${tag("Работает")}</div></div>${link("Все проверки","system.html","","pulse")}</div></section>`;
  }
  function queue(){
    return `<div class="metrics">${metric("Всего в очередях","8","активных заявок")}${metric("Высокий приоритет","3","требуют внимания первым","red")}${metric("Среднее ожидание","7,4 мин","цель — менее 10 минут","blue")}${metric("Следующее действие","Волкова","открыть карточку","amber")}</div><section class="section card table-card"><div class="table-top"><div><h2>Независимые очереди стран</h2><small id="queue-count">6 заявок отображается</small></div>${tag("FIFO с учётом приоритета")}</div><div class="filters"><select class="select" id="queue-country"><option>Все страны</option><option>Италия</option><option>Испания</option><option>Франция</option><option>Турция</option><option>ОАЭ</option><option>Греция</option></select><select class="select" id="queue-priority"><option>Все приоритеты</option><option>Высокий</option><option>Средний</option><option>Низкий</option></select><div class="search-wrap">${icon("search")}<input class="input" id="queue-search" placeholder="Поиск по клиенту или стране"></div></div><div class="table-scroll"><table><thead><tr><th>Позиция</th><th>Клиент</th><th>Страна</th><th>Приоритет</th><th>Статус</th><th>Ожидание</th><th>Следующий шаг</th><th></th></tr></thead><tbody id="queue-body"></tbody></table><div class="empty" id="queue-empty" hidden>${icon("search")}<p>По этому фильтру заявок нет</p></div></div></section>`;
  }
  function customersPage(){
    return `<section class="section split"><div class="card table-card"><div class="table-top"><div><h2>Клиентская база</h2><small id="customer-count">5 из 5 записей</small></div><button class="icon-button" data-action="toast" data-message="Фильтры клиентов">${icon("filter")}</button></div><div class="filters"><div class="search-wrap">${icon("search")}<input class="input" id="customer-search" placeholder="Имя, email или страна"></div><select class="select"><option>Все статусы</option><option>В работе</option><option>Завершён</option></select></div><div class="table-scroll"><table><thead><tr><th>Клиент</th><th>Страна</th><th>Записей</th><th>Последняя активность</th><th>Статус</th></tr></thead><tbody id="customer-body"></tbody></table><div class="empty" id="customer-empty" hidden>${icon("users")}<p>Клиенты не найдены</p></div></div></div><div class="card card-pad" id="customer-card"></div></section>`;
  }
  function monitoring(){
    const m=[["Booking gateway","Основной API записи · 182 мс","Все проверки пройдены","99,98%","good"],["Платёжный шлюз","CloudPayments · 241 мс","Все проверки пройдены","99,95%","good"],["Почтовый канал","SMTP relay · 408 мс","Есть задержка ответа","99,71%","warn"],["Календарь операторов","Внутренний сервис · 86 мс","Все проверки пройдены","100%","good"]];
    return `<div class="metrics">${metric("Сервисы онлайн","4 / 4","без критических сбоев","teal")}${metric("Средний ответ","229 мс","за последние 15 минут","blue")}${metric("Ошибки за час","3","на 0,4% меньше нормы","amber")}${metric("SLA сегодня","99,7%","цель — 99,5%","teal")}</div><section class="section split"><div class="card table-card"><div class="table-top"><div><h2>Проверки сервисов</h2><small>Автопроверка каждые 60 секунд</small></div>${tag("Работает")}</div>${m.map(x=>`<div class="check" style="padding:18px 19px"><div><div class="check-name">${x[0]}</div><div class="check-meta">${x[1]}</div></div><div style="text-align:right"><div class="check-status ${x[4]==="warn"?"warn":""}"><span class="health-dot ${x[4]==="warn"?"warn":""}"></span>${x[2]}</div><div class="subtext" style="margin-top:5px">${x[3]} доступность</div></div></div>`).join("")}</div><div class="card card-pad"><div class="section-head"><div><h2>Задержка ответа</h2><small>booking-gateway · мс</small></div><span class="kicker">15 мин</span></div>${bars([35,38,42,39,44,48,51,46,58,49,52,61,56,64,58,68,71,65])}<div class="stat-row"><span>Текущее</span><strong>182 мс</strong></div><div class="stat-row"><span>Пик</span><strong>408 мс</strong></div><div class="section"><h3>Последний инцидент</h3><p class="panel-note">В 10:32 почтовый канал отвечал с задержкой 1,8 сек. Сервис восстановился автоматически.</p></div></div></section>`;
  }
  function notificationsPage(){
    return `<div class="tabs"><button class="tab active" data-tab="all">Все <span>4</span></button><button class="tab" data-tab="unread">Непрочитанные <span>2</span></button></div><section class="section card table-card"><div class="table-top"><div><h2>Лента уведомлений</h2><small>Последнее обновление — сегодня в 11:57</small></div>${tag("2 требуют реакции","red")}</div><div id="notice-list">${notifications.map(n=>notice(n)).join("")}</div></section>`;
  }
  function notice(n){return `<div class="notice-row ${n[4]?"unread":"read"}" data-notice="${n[0]}" data-unread="${n[4]}"><span class="notice-mark"></span><div class="notice-copy"><strong>${n[1]}</strong>${n[2]}<div class="notice-time">${n[3]}</div></div>${n[4]?`<button class="notice-action" data-action="read" data-id="${n[0]}">Прочитано</button>`:""}${tag(n[6],n[5])}</div>`}
  function eventsPage(){return `<section class="card table-card"><div class="filters"><div class="search-wrap">${icon("search")}<input class="input" id="events-search" placeholder="Поиск по журналу"></div><select class="select" id="events-kind"><option>Все события</option><option>Новая запись</option><option>Платёж</option><option>Система</option><option>Смена</option><option>Алерт</option></select><button class="button" data-action="toast" data-message="Фильтры применены">${icon("filter")}Фильтры</button></div><div class="table-scroll"><table><thead><tr><th>Время</th><th>Событие</th><th>Контекст</th><th>Тип</th><th>Источник</th></tr></thead><tbody id="events-body"></tbody></table><div class="empty" id="events-empty" hidden>${icon("file")}<p>События не найдены</p></div></div></section>`}
  function system(){const c=[["Основной контур бронирования","booking-gateway / v2.8.4","182 мс","Работает","good"],["Слой данных клиентов","customer-store / primary","86 мс","Работает","good"],["Почтовые уведомления","smtp-relay / eu-central-1","408 мс","Наблюдение","warn"],["Очередь фоновых задач","worker-pool / 4 workers","12 задач","Работает","good"],["Резервное копирование","backup-vault / 04:00 UTC","сегодня","Работает","good"]];return `<div class="metrics">${metric("Общий статус","Стабильно","5 из 5 контуров доступны","teal")}${metric("Доступность за 30 дней","99,96%","выше целевого SLA","blue")}${metric("Активных задач","12","очередь обрабатывается","amber")}${metric("Последний backup","04:00","сегодня · без ошибок","teal")}</div><section class="section split"><div class="card table-card"><div class="table-top"><div><h2>Контуры системы</h2><small>Проверено сегодня в 11:57:24</small></div>${tag("Все системы")}</div>${c.map(x=>`<div class="check" style="padding:16px 19px"><div><div class="check-name">${x[0]}</div><div class="check-meta">${x[1]}</div></div><div style="text-align:right"><div class="check-status ${x[4]==="warn"?"warn":""}"><span class="health-dot ${x[4]==="warn"?"warn":""}></span>${x[3]}</div><div class="subtext" style="margin-top:4px">${x[2]}</div></div></div>`).join("")}</div><div class="card card-pad"><div class="section-head"><div><h2>Ресурсы контура</h2><small>Текущее использование</small></div>${icon("gauge")}</div><div class="stat-row"><span>CPU</span><span>38%</span></div>${progress("38%")}<div class="stat-row"><span>Память</span><span>61%</span></div>${progress("61%","amber")}<div class="stat-row"><span>Хранилище</span><span>47%</span></div>${progress("47%")}<div class="section"><h3>Дежурный инженер</h3><div class="activity-item"><div class="activity-icon">${icon("life")}</div><div class="activity-copy"><strong>Илья Воронцов</strong><div class="subtext">На линии до 14:00 · #infra-duty</div></div></div></div></div></section>`}
  function settings(){const rows=[["auto","Автообновление очереди","Обновлять данные каждые 60 секунд во время активной смены.",true],["sound","Звуковые сигналы","Воспроизводить короткий сигнал для алертов высокого приоритета.",false],["completed","Показывать завершённые","Оставлять завершённые заявки в журнале очереди на 24 часа.",false],["handoff","Напоминание о передаче","Показать напоминание за 30 минут до окончания смены.",true]];return `<section class="settings-grid section"><div class="card card-pad"><div class="section-head"><div><h2>Поведение интерфейса</h2><small>Параметры текущего оператора</small></div>${icon("settings")}</div>${rows.map(x=>`<div class="settings-row"><div><div class="settings-label">${x[1]}</div><div class="settings-desc">${x[2]}</div></div><button class="toggle ${getSetting(x[0],x[3])?"on":""}" data-setting="${x[0]}" aria-label="${x[1]}"><i></i></button></div>`).join("")}</div><div class="card card-pad"><div class="section-head"><div><h2>Профиль оператора</h2><small>Как вас видит команда</small></div><div class="avatar">АК</div></div><div class="form-group"><label class="form-label">Имя и фамилия</label><input class="input full-input" value="Анна Кузнецова"></div><div class="form-group"><label class="form-label">Рабочий email</label><input class="input full-input" value="anna.kuznetsova@bookingops.ru"></div><div class="form-group"><label class="form-label">Часовой пояс</label><select class="select full-input"><option>Москва (UTC+3)</option><option>Екатеринбург (UTC+5)</option></select></div>${button("Обновить профиль","primary","check")}</div></section><section class="section card card-pad"><div class="section-head"><div><h2>Правила очереди</h2><small>Общие настройки распределения</small></div><a class="button" href="queue.html">Открыть очередь</a></div><div class="settings-row"><div><div class="settings-label">Сначала срочные</div><div class="settings-desc">Высокий приоритет всегда поднимается выше времени создания.</div></div>${tag("Активно")}</div><div class="settings-row"><div><div class="settings-label">Лимит ожидания</div><div class="settings-desc">Заявка отмечается жёлтым после 10 минут ожидания.</div></div>${tag("10 минут","amber")}</div></section>`}
  function getSetting(k,d){try{const x=JSON.parse(localStorage.getItem("booking-ops-settings")||"{}");return x[k]===undefined?d:x[k]}catch(e){return d}}
  function reports(){return `<div class="filters" style="padding:0;border:0;margin-bottom:21px"><select class="select"><option>Последние 7 дней</option><option>Последние 30 дней</option><option>Текущий месяц</option></select><button class="button">${icon("calendar")} Последние 7 дней</button></div><div class="metrics">${metric("Всего заявок","318","+12,6% к прошлой неделе","teal")}${metric("Среднее время обработки","18,4 мин","на 2,1 мин быстрее","blue")}${metric("В пределах SLA","92,4%","цель команды — 90%","amber")}${metric("CSAT","4,8","из 5,0 · 84 ответа","teal")}</div><section class="section report-grid"><div class="card card-pad"><div class="section-head"><div><h2>Поток заявок</h2><small>Создано и завершено по дням</small></div>${tag("Последние 7 дней")}</div><div class="chart">${[58,68,44,76,84,63,91].map((v,i)=>`<div class="chart-col"><i style="height:${v}%"></i><small>${["Пн","Вт","Ср","Чт","Пт","Сб","Вс"][i]}</small></div>`).join("")}</div><div class="mini-grid" style="margin-top:18px"><div class="mini-stat"><label>Создано</label><strong>318</strong></div><div class="mini-stat"><label>Завершено</label><strong>294</strong></div><div class="mini-stat"><label>В очереди</label><strong>24</strong></div></div></div><div class="card card-pad"><div class="section-head"><div><h2>По странам</h2><small>Доля активных заявок</small></div>${icon("more")}</div>${[["Италия","36%"],["Испания","24%"],["Франция","18%"],["Турция","13%"],["Другие","9%"]].map(x=>`<div><div class="stat-row"><span>${x[0]}</span><span>${x[1]}</span></div>${progress(x[1],x[0]==="Испания"?"amber":"")}</div>`).join("")}</div></section>`}
  function shifts(){return `<div class="metrics">${metric("Операторов онлайн","4","из 5 в расписании","teal")}${metric("Текущая смена","08:30—12:30","до передачи 33 минуты","amber")}${metric("Заявок на оператора","2,0","равномерная нагрузка","blue")}${metric("Передач сегодня","7","без пропущенных контекстов","teal")}</div><section class="section split"><div class="card card-pad"><div class="section-head"><div><h2>Текущая смена</h2><small>Пятница, 28 июня</small></div>${tag("В эфире")}</div><div class="shift-current"><div><span>Смена 08:30—12:30</span><strong>Утренняя операционная</strong></div><div class="shift-avatar">АК</div></div>${[["АК","Анна Кузнецова","Основной оператор"],["МО","Михаил Орлов","Резервный оператор"],["ДМ","Дарья Мельник","Контроль качества"]].map(x=>`<div class="check">${person(x,x[2])}${tag(x[1]==="Анна Кузнецова"?"На линии":"Онлайн")}</div>`).join("")}</div><div class="card card-pad"><div class="section-head"><div><h2>Расписание</h2><small>Ближайшие смены</small></div><a class="table-link" href="settings.html">Настроить</a></div>${[["Сегодня","Анна Кузнецова","08:30—12:30"],["Сегодня","Павел Соколов","12:30—16:30"],["Сегодня","Михаил Орлов","16:30—20:30"],["Завтра","Дарья Мельник","08:30—12:30"]].map(x=>`<div class="schedule-row"><span class="schedule-day">${x[0]}</span><span class="schedule-name">${x[1]}</span><span class="schedule-time">${x[2]}</span></div>`).join("")}</div></section><section class="section card card-pad"><div class="section-head"><div><h2>Передача контекста</h2><small>Чек-лист перед завершением смены</small></div>${tag("1 шаг остался","amber")}</div>${[["Очередь очищена от просроченных заявок",true],["Комментарий добавлен к заявке #BK-2841",true],["Следующий оператор ознакомлен с алертами",false]].map(x=>`<div class="settings-row"><div class="settings-label">${x[0]}</div>${tag(x[1]?"Готово":"Проверить",x[1]?"":"amber")}</div>`).join("")}</section>`}
  function quality(){const rows=[["Ткаченко Ольга Игоревна","Анна Кузнецова","98%","Чёткая коммуникация"],["Иванов Пётр Сергеевич","Михаил Орлов","94%","Документ проверен позже SLA"],["Смирнова Анна Викторовна","Анна Кузнецова","100%","Без замечаний"],["Петрова Елена","Дарья Мельник","91%","Нужен комментарий к оплате"]];return `<div class="tabs"><button class="tab active">Обзор</button><button class="tab">Проверки <span>24</span></button><button class="tab">Отклонения <span>3</span></button></div><section class="section metrics">${metric("Средняя оценка","95,7%","+1,8% к прошлой неделе","teal")}${metric("Проверено записей","24","из 47 завершённых","blue")}${metric("Отклонения","3","требуют обратной связи","red")}${metric("CSAT клиентов","4,8 / 5","84 ответа","amber")}</section><section class="section split"><div class="card table-card"><div class="table-top"><div><h2>Последние проверки</h2><small>Оценка по стандарту Booking Ops</small></div>${tag("Период: 7 дней")}</div><div class="table-scroll"><table><thead><tr><th>Клиент</th><th>Оператор</th><th>Оценка</th><th>Комментарий</th></tr></thead><tbody>${rows.map(x=>`<tr><td class="person-name">${x[0]}</td><td>${x[1]}</td><td class="${x[2]==="91%"?"priority-medium":"priority-low"}">${x[2]}</td><td class="subtext">${x[3]}</td></tr>`).join("")}</tbody></table></div></div><div class="card card-pad"><div class="section-head"><div><h2>Распределение оценки</h2><small>По критериям проверки</small></div>${icon("spark")}</div><div class="quality-bars">${[["Точность данных","98%"],["Скорость реакции","93%"],["Тон общения","97%"],["Работа с рисками","91%"]].map(x=>`<div class="quality-line"><span>${x[0]}</span>${progress(x[1])}<span>${x[1]}</span></div>`).join("")}</div><div class="section"><div class="quality-score"><div class="score-ring">95,7</div><div><h3>Стабильный результат</h3><p class="panel-note">Команда выше целевого показателя третью неделю подряд.</p></div></div></div></div></section>`}
  function integrations(){const xs=[["calendar","CAL","Календарь бронирований","Синхронизация доступности и подтверждений записей.","Синхронизировано 2 мин назад",true],["payments","PAY","CloudPayments","Проверка статуса оплаты и возвратов в реальном времени.","Синхронизировано 4 мин назад",true],["mail","SMTP","Почтовый канал","Системные письма, подтверждения и уведомления клиентов.","Синхронизировано 8 мин назад",true],["crm","CRM","CRM компании","Передача карточек клиентов в коммерческий контур.","Подключение не завершено",false]];return `<div class="metrics">${metric("Подключений активно","3","из 4 настроенных","teal")}${metric("Событий сегодня","1 284","входящие и исходящие","blue")}${metric("Ошибок синхронизации","2","повтор отправки запланирован","amber")}${metric("Последняя проверка","11:57","все каналы проверены","teal")}</div><section class="section integration-grid">${xs.map(x=>`<div class="card integration"><div class="integration-head"><div class="integration-logo">${x[1]}</div><button class="toggle ${x[5]?"on":""}" data-integration="${x[0]}" aria-label="Переключить ${x[2]}"><i></i></button></div><h3>${x[2]}</h3><p>${x[3]}</p><div class="integration-footer"><span>${x[4]}</span><span class="health-dot ${x[5]?"":"down"}"></span></div></div>`).join("")}</section><section class="section card card-pad"><div class="section-head"><div><h2>Последние события интеграций</h2><small>Входящие и исходящие операции</small></div><a class="table-link" href="events.html">Открыть журнал</a></div>${[["11:54","CloudPayments","Платёж подтверждён для #BK-2841","teal"],["11:46","Календарь бронирований","Создан слот для Италии · 14:30","blue"],["11:34","Почтовый канал","Повтор отправки уведомления #NT-392","amber"]].map(x=>`<div class="check"><div><div class="check-name">${x[1]}</div><div class="check-meta">${x[2]}</div></div>${tag(x[0],x[3])}</div>`).join("")}</section>`}
  function renderTableRows(){
    const q=document.getElementById("queue-body"); if(q){const s=(document.getElementById("queue-search").value||"").toLowerCase(),c=document.getElementById("queue-country").value,p=document.getElementById("queue-priority").value;const rows=queueRows.filter(r=>(!s||(r[1]+" "+r[2]).toLowerCase().includes(s))&&(c==="Все страны"||r[2]===c)&&(p==="Все приоритеты"||r[3]===p));q.innerHTML=rows.map((r,i)=>`<tr><td><span class="queue-num">${i+1}</span></td><td>${person(r,r[7])}</td><td>${r[2]}</td><td class="priority-${r[3]==="Высокий"?"high":r[3]==="Средний"?"medium":"low"}">${r[3]}</td><td>${tag(r[4],r[8])}</td><td>${r[5]}</td><td><span class="subtext">${r[6]}</span></td><td><a class="button" href="customers.html">Открыть</a></td></tr>`).join("");document.getElementById("queue-count").textContent=rows.length+" заявок отображается";document.getElementById("queue-empty").hidden=rows.length!==0}
    const cu=document.getElementById("customer-body");if(cu){const s=(document.getElementById("customer-search").value||"").toLowerCase(),rows=customers.filter(r=>(r.join(" ").toLowerCase().includes(s)));cu.innerHTML=rows.map((r,i)=>`<tr data-customer="${i}"><td>${person(r,r[2])}</td><td>${r[3]}</td><td>${r[4]}</td><td class="subtext">${r[5]}</td><td>${tag(r[6],r[6]==="В работе"?"teal":"blue")}</td></tr>`).join("");document.getElementById("customer-count").textContent=rows.length+" из "+customers.length+" записей";document.getElementById("customer-empty").hidden=rows.length!==0;cu.querySelectorAll("[data-customer]").forEach(tr=>tr.addEventListener("click",()=>showCustomer(Number(tr.dataset.customer))))}
    const ev=document.getElementById("events-body");if(ev){const s=(document.getElementById("events-search").value||"").toLowerCase(),k=document.getElementById("events-kind").value,rows=events.filter(e=>(!s||e.join(" ").toLowerCase().includes(s))&&(k==="Все события"||e[3]===k));ev.innerHTML=rows.map(e=>`<tr><td class="subtext">${e[0]}</td><td>${person([e[3].slice(0,2).toUpperCase(),e[1]],"")}</td><td>${e[2]}</td><td>${tag(e[3],e[4])}</td><td class="subtext">${e[3]==="Система"?"Автоматика":"Анна Кузнецова"}</td></tr>`).join("");document.getElementById("events-empty").hidden=rows.length!==0}
  }
  function showCustomer(i){const r=customers[i]||customers[0],el=document.getElementById("customer-card");if(!el)return;el.innerHTML=`<div class="section-head"><div><p class="eyebrow">Карточка клиента</p><h2>${r[1]}</h2></div><button class="icon-button" data-action="toast" data-message="Дополнительные действия">${icon("more")}</button></div>${person(r,r[2]+" · "+r[3])}<div class="section"><div class="stat-row"><span>Текущий статус</span>${tag(r[6])}</div><div class="stat-row"><span>Последняя активность</span><span>${r[5]}</span></div><div class="stat-row"><span>Средняя оценка</span><span>4,8 / 5</span></div></div><div class="section"><h3>Последние записи</h3><div class="check"><div><div class="check-name">Заявка #BK-2841</div><div class="check-meta">Рим · сегодня, 11:42</div></div>${tag("Оплата","amber")}</div><div class="check"><div><div class="check-name">Заявка #BK-2710</div><div class="check-meta">Милан · 12 июня</div></div>${tag("Завершена")}</div></div><a class="button" style="width:100%;margin-top:19px" href="queue.html">Открыть в очереди</a>`}
  function toast(text){const el=document.getElementById("toast");if(!el)return;el.textContent=text;el.hidden=false;clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.hidden=true,2400)}
  function init(){
    const file=(location.pathname.split("/").pop()||"index.html")||"index.html",p=pages[file]||pages["index.html"];document.title=p.title+" — Booking Ops";
    let content=p.key==="dashboard"?dashboard():p.key==="queue"?queue():p.key==="customers"?customersPage():p.key==="monitoring"?monitoring():p.key==="notifications"?notificationsPage():p.key==="events"?eventsPage():p.key==="system"?system():p.key==="settings"?settings():p.key==="reports"?reports():p.key==="shifts"?shifts():p.key==="quality"?quality():integrations();
    document.body.innerHTML=shell(p.key,content);
    renderTableRows();showCustomer(0);
    document.addEventListener("input",e=>{if(["queue-search","customer-search","events-search"].includes(e.target.id))renderTableRows()});
    document.addEventListener("change",e=>{if(["queue-country","queue-priority","events-kind"].includes(e.target.id))renderTableRows()});
    document.addEventListener("click",e=>{const el=e.target.closest("[data-action]");if(!el)return;const a=el.dataset.action;if(a==="menu")document.getElementById("sidebar").classList.toggle("open");if(a==="bell"){const x=document.getElementById("notification-pop");x.hidden=!x.hidden}if(a==="toast")toast(el.dataset.message||"Готово");if(a==="read"){const row=document.querySelector(`[data-notice="${el.dataset.id}"]`);row.classList.remove("unread");row.classList.add("read");el.remove();toast("Уведомление отмечено прочитанным")}});
    document.addEventListener("click",e=>{const t=e.target.closest("[data-setting]");if(t){const k=t.dataset.setting;const v=!t.classList.contains("on");t.classList.toggle("on",v);try{const x=JSON.parse(localStorage.getItem("booking-ops-settings")||"{}");x[k]=v;localStorage.setItem("booking-ops-settings",JSON.stringify(x))}catch(_){}}const i=e.target.closest("[data-integration]");if(i){i.classList.toggle("on");const dot=i.closest(".integration").querySelector(".health-dot");dot.classList.toggle("down",!i.classList.contains("on"));toast("Статус интеграции изменён")}});
    const readAll=document.querySelector("[data-message='Отметить все прочитанными']");if(readAll)readAll.addEventListener("click",()=>{document.querySelectorAll(".notice-row.unread").forEach(r=>{r.classList.remove("unread");r.classList.add("read");const b=r.querySelector(".notice-action");if(b)b.remove()});toast("Все уведомления прочитаны")});
    document.querySelectorAll(".tab").forEach(t=>t.addEventListener("click",()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));t.classList.add("active");if(t.dataset.tab==="unread")document.querySelectorAll(".notice-row").forEach(r=>r.hidden=r.dataset.unread!=="true");else document.querySelectorAll(".notice-row").forEach(r=>r.hidden=false)}));
    document.querySelectorAll("[data-action='toast']").forEach(b=>b.addEventListener("click",()=>{if(b.dataset.message==="Обновить"){document.getElementById("sync-time").textContent=new Date().toLocaleTimeString("ru-RU",{hour:"2-digit",minute:"2-digit"});toast("Данные обновлены")}}));
  }
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();
})();